# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0085_auto_20170228_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='freeze_edition',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
