# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0086_book_freeze_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_find', models.BooleanField(default=False)),
                ('savings_new', models.FloatField(blank=True, db_index=True, default=1.0)),
                ('savings_used', models.FloatField(blank=True, db_index=True, default=1.0)),
                ('votes', models.IntegerField(null=True)),
                ('rank', models.IntegerField(db_index=True)),
                ('current_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='books.Book')),
                ('previous_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='books.Book')),
            ],
        ),
    ]
