# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0087_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookscore',
            name='most_recent_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.SalesRank'),
        ),
    ]
