# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0089_auto_20170909_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
